### ISSUE TITLE
master branch is broken status on rubyci

### ISSUE THREAD

**Issue by hsbt** [ruby/rubyspec#38] opened 2015-02-25 07:16 UTC
see http://rubyci.blob.core.windows.net/centos7/ruby-trunk/log/20150225T050002Z.fail.html.gz

I investigate this. I found some broken specs.

1. mkdir work (it's temporary dir)
2. git clone mspec
3. git clone rubyspec
4. run follow command

```sh
$ ruby mspec/bin/mspec -fd rubyspec/core/argf/codepoints_spec.rb
```

I got this fail.

```
% ruby mspec/bin/mspec -fd rubyspec/core/argf/codepoints_spec.rb
ruby 2.1.5p299 (2015-02-19 revision 49652) [x86_64-darwin14.0]
E....

1)
An exception occurred during: after :each
ARGF.codepoints is a public method ERROR
Errno::ENOENT: No such file or directory @ rb_sysopen - -fd
/Users/(snip)/rubyspec/core/argf/shared/each_codepoint.rb:12:in `closed?'
```

**Comment by hsbt** [comment] 2015-02-25 07:17
I changed default branch to ```ruby``` and force pushed yesterday status. because we have release plan of new version of Ruby in this month.

**Comment by eregon** [comment] 2015-02-25 08:53
I cannot reproduce with `ruby 2.3.0dev (2015-02-25 trunk 49725) [x86_64-linux]`, any idea what might be the cause?
I did:
```
mkdir work
cd work
git clone git@github.com:ruby/mspec.git
git clone git@github.com:ruby/rubyspec.git
cd mspec  && git checkout master && cd ..
cd rubyspec  && git checkout master && cd ..
ruby mspec/bin/mspec -fd rubyspec/core/argf/codepoints_spec.rb
ruby 2.3.0dev (2015-02-25 trunk 49725) [x86_64-linux]
.....

Finished in 0.001261 seconds

1 file, 5 examples, 5 expectations, 0 failures, 0 errors
```

**Comment by hsbt** [comment] 2015-02-25 08:56
I already fixed codepoinsts_spec.rb

**Comment by hsbt** [comment] 2015-02-25 08:57
@nobu and me fixed some specs, but following examples still failed. Please see this lists: https://gist.github.com/hsbt/df6cf7bb7029c6cdb691

**Comment by eregon** [comment] 2015-02-25 09:03
These failure seem to only happen when you run with cwd above the rubyspec and mspec directories, right?
I am used to run locally in the rubyspec dir like this:
```
ruby ../mspec/bin/mspec -fd core/file/to_path_spec.rb     
```

**Comment by hsbt** [comment] 2015-02-25 09:06
> These failure seem to only happen when you run with cwd above the rubyspec and mspec directories, right?

Yes. but rubyci uses mspec and rubyspec outside their directory.

**Comment by eregon** [comment] 2015-02-25 09:16
This is due (at least the first of the list) to lack of specifying the config file, for instance
```
$ ruby mspec/bin/mspec --config rubyspec/ruby.2.3.mspec -fd rubyspec/core/file/to_path_spec.rb
passes
but
ruby mspec/bin/mspec -fd rubyspec/core/file/to_path_spec.rb
not
```

Now, I do agree this is still a bug in rubyspec in that that final test should be guarded with
`with_feature :encoding do`, but I would think Ruby CI should use the config file to enable encoding specs, no?
Or do you run both with and without config on Ruby CI?

**Comment by eregon** [comment] 2015-02-25 09:20
In particular, http://www.rubyist.net/~akr/chkbuild/debian/ruby-trunk/log/20150225T064600Z.log.html.gz#rubyspec uses `rubyspec/ruby.1.9.mspec` which does not exist!
MSpec should definitely not swallow the error, but this should be changed to ruby.2.3.mspec (or ruby.mspec if you agree on https://github.com/ruby/mspec/issues/4).

**Comment by hsbt** [comment] 2015-02-25 09:25
Note: chkbuild is https://github.com/akr/chkbuild

**Comment by eregon** [comment] 2015-02-25 10:13
Do you want to fix these failures due to lack of config file?

**Comment by eregon** [comment] 2015-02-25 10:50
Should master be the default branch again?

**Comment by eregon** [comment] 2015-02-25 12:12
I will fix the one related to the encode helper.

**Comment by eregon** [comment] 2015-02-25 13:58
Closing this one as it is getting quite long, please reopen if there is any issue :)

**Closed by eregon** 2015-02-25 13:58 UTC

**Comment by hsbt** [comment] 2015-02-26 00:33
@eregon I changed default branch to ```master```, Now, some examples are still fails. I will create new issue.
